weights: ./runs/train/exp10/weights/last.pt
cfg: ''
data: data/mask.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 100
batch_size: 4
imgsz: 640
rect: false
resume: true
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 0
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
freeze: 0
patience: 30
save_dir: runs/train/exp10
